### ISSUE TITLE
Freedesktop notifications wrapper

### ISSUE THREAD

**Issue by plfiorini** [hawaii-desktop/libhawaii#5]
Make a Qt-style wrapper for xdg notifications that can also be used from QML

**Comment by iBelieve** [comment]
Maybe this should go in Fluid and be implemented in such a way that someone could add support for notifications on other platforms?

**Comment by plfiorini** [comment]
It's too complex for Fluid as it would need some sort of QPA architecture, actually looks like Qt is going that route: https://codereview.qt-project.org/#/c/97068/
For now we should put it into the platform-dependant library.
